CREATE TABLE message (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body VARCHAR(2000) NOT NULL,
    insert_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
